import type { Metadata } from "next";
import { AppProvider } from "../context/AppContext";

import "./globals.css";



export const metadata: Metadata = {
  title: "ChatApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <AppProvider> {children}</AppProvider>
      </body>
    </html>
  );
}
